-- MySQL Script generated by MySQL Workbench
-- 2016年06月29日 15時06分12秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema push
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `push` ;

-- -----------------------------------------------------
-- Schema push
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `push` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `push` ;

-- -----------------------------------------------------
-- Table `push`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `push`.`user` ;

CREATE TABLE IF NOT EXISTS `push`.`user` (
  `table_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `table_key` VARCHAR(20) NOT NULL,
  `name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NOT NULL,
  `google_id` VARCHAR(255) NULL,
  `google_link` VARCHAR(255) NULL,
  `gcm_key` VARCHAR(50) NULL,
  `gcm_project_number` VARCHAR(50) NULL,
  `flg_active` VARCHAR(3) NOT NULL,
  `add_datetime` DATETIME NOT NULL,
  `update_datetime` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`table_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `push`.`subscriber_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `push`.`subscriber_list` ;

CREATE TABLE IF NOT EXISTS `push`.`subscriber_list` (
  `subscription_id` VARCHAR(255) NOT NULL,
  `terminal` VARCHAR(20) NULL,
  `browser` VARCHAR(20) NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `geoError` TINYINT NULL,
  `add_datetime` DATETIME NOT NULL,
  `address1` VARCHAR(255) NULL COMMENT '都道府県',
  `address2` VARCHAR(255) NULL COMMENT '市区町村',
  `address3` VARCHAR(255) NULL,
  PRIMARY KEY (`subscription_id`))
ENGINE = InnoDB
COMMENT = 'どのuserのリスト�' /* comment truncated */ /*��は判断していない。
判別するときは別途ロジックを組む必要がある
*/;

CREATE INDEX `subscription_id` ON `push`.`subscriber_list` (`subscription_id` ASC);


-- -----------------------------------------------------
-- Table `push`.`push_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `push`.`push_log` ;

CREATE TABLE IF NOT EXISTS `push`.`push_log` (
  `table_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_table_id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `message` TEXT NOT NULL,
  `link` TEXT NULL,
  `count` INT NULL DEFAULT 0,
  `add_datetime` DATETIME NOT NULL,
  PRIMARY KEY (`table_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `push`.`show_notification_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `push`.`show_notification_log` ;

CREATE TABLE IF NOT EXISTS `push`.`show_notification_log` (
  `push_log_table_id` INT UNSIGNED NOT NULL,
  `subscription_id` VARCHAR(255) NOT NULL,
  `add_datetime` DATETIME NOT NULL)
ENGINE = InnoDB;

CREATE INDEX `index1` ON `push`.`show_notification_log` (`push_log_table_id` ASC);


-- -----------------------------------------------------
-- Table `push`.`click_notification_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `push`.`click_notification_log` ;

CREATE TABLE IF NOT EXISTS `push`.`click_notification_log` (
  `push_log_table_id` INT UNSIGNED NOT NULL,
  `subscription_id` VARCHAR(255) NOT NULL,
  `add_datetime` DATETIME NOT NULL)
ENGINE = InnoDB;

CREATE INDEX `index1` ON `push`.`click_notification_log` (`push_log_table_id` ASC);


-- -----------------------------------------------------
-- Table `push`.`error_notification_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `push`.`error_notification_log` ;

CREATE TABLE IF NOT EXISTS `push`.`error_notification_log` (
  `subscription_id` VARCHAR(255) NOT NULL,
  `error` TEXT NOT NULL,
  `add_datetime` DATETIME NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `push`.`session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `push`.`session` ;

CREATE TABLE IF NOT EXISTS `push`.`session` (
  `id` VARCHAR(32) NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  `modified` INT UNSIGNED NOT NULL,
  `lifetime` INT UNSIGNED NOT NULL,
  `data` TEXT NOT NULL,
  PRIMARY KEY (`id`, `name`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
