<div class="row">
    <div class="col-md-12">
        <div class="text-center">
            <h2>処理中...</h2>
            <div style="margin:20px 0;"><img src="/img/icon_waiting.gif" height="65px">
            </div>
            <p>
                このままお待ちください
            </p>
        </div>
    </div>
</div>

<script>
    var path = '<?php echo $this->escapeJs($this->next['path']);?>';
    <?php if($this->next['query'] === false): ?>
        var query = false;
    <?php else:?>
        var query = '?<?php echo $this->escapeJs($this->next['query']); ?>';
    <?php endif;?>

    <?php if($this->next['fragment'] === false): ?>
        var fragment = false;
    <?php else:?>
        var fragment = '#<?php echo $this->escapeJs($this->next['fragment']);?>';
    <?php endif;?>

    setTimeout(function(){
        var loc = path;
        if(query) loc += query;
        if(fragment) loc += fragment;
        document.location.href = loc;
    }, 10);
</script>
